### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by Ragamuffin-Asa** [Romanysoft/MarkdownD#1]
I'm really new to coding and such, so I bought MarkdownD for it's handy PDFexport function. But it's not working properly.

I followed the online tutorial on your website: http://romanysoft.github.io/MarkdownD/documents.html
But when I follow those instructions, the layout is all messed up.

Here are some screenshots to give an example:

This is the MarkdownD document:
![markdownd01](https://cloud.githubusercontent.com/assets/18027388/13981916/4c8870fa-f0e7-11e5-973c-64b124f64410.jpg)

![markdownd02](https://cloud.githubusercontent.com/assets/18027388/13981932/5ab9462c-f0e7-11e5-98ca-712111b431be.jpg)

This is how the pdf turns out, after exporting it:
![markdownd03](https://cloud.githubusercontent.com/assets/18027388/13981934/605b0ef8-f0e7-11e5-96fa-8486f858c9f4.jpg)
As you can see: not the entire document is exported, the layout is wrong, there are no images, hyperlinks don't work etc.

I hope someone can help.

**Comment by lauer3912** [comment]
@Ragamuffin-Asa 

Hi! Watch the following video zip file.

[export_as_pdf_macos.zip](https://github.com/Romanysoft/MarkdownD/files/189101/export_as_pdf_macos.zip)

**Comment by Ragamuffin-Asa** [comment]
@lauer3912 

Thanks for your response!  It does not solve the issue, however. 
Most importantly, it only exports a small fragment of my document. 

Here's a video where I follow your instructions and where you can see not all the pages are exported. Hope you can help.
[ProblemMarkdownD1.zip](https://github.com/Romanysoft/MarkdownD/files/191026/ProblemMarkdownD1.zip)

**Comment by lauer3912** [comment]
@Ragamuffin-Asa 

Thanks for your feedback! We have to fix the bug as soon as possible.
Below is the indirect method, we hope to help you.
Watch the following video file. 
[export_as_pdf_macos_usePrint](https://github.com/Romanysoft/MarkdownD/blob/master/issues/export_as_pdf_macos_usePrint.mp4)

**Comment by Ragamuffin-Asa** [comment]
Thank you! It at least exports all the pages now. I only need to watch out for the images not being too large. 

If you'd allow me, here is some other feedback on the PDF export:
1. The Table of Contents [TOC] function doesn't work properly, The links don't direct you to the chapters, but to a new MarkDownD document.
2. In the pdf there's a header with the name of you document, can this be removed? 
   ![markdownd_pdf_and_pdf_export_ _issue__1_ _romanysoft_markdownd_and_problemmarkdownd1_zip_openen](https://cloud.githubusercontent.com/assets/18027388/14100812/60fd0d90-f590-11e5-92f9-bcf418837c8b.jpg)

Hope it's a little useful!

**Comment by lauer3912** [comment]
@Ragamuffin-Asa Try new version 

https://romanysoft.github.io/MarkdownD/versions
