### ISSUE TITLE
empty table preview

### ISSUE THREAD

**Issue by sugarwyc** [Romanysoft/MarkdownD#3]
![68c6999c-655c-4c3f-80f7-078bdb27bff3](https://cloud.githubusercontent.com/assets/5518603/16029407/5c8a91d4-321b-11e6-94da-7f13c774191a.png)

**Comment by lauer3912** [comment]
@sugarwyc Thanks for your feedback!  We fixed  #2 [https://github.com/Romanysoft/MarkdownD/wiki/Changelog](https://github.com/Romanysoft/MarkdownD/wiki/Changelog)

download: https://romanysoft.github.io/MarkdownD/versions
