### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by 1iveowl** [Romanysoft/MarkdownD#4]
Unable to register MarkdownD 3.6.0 on Windows 10

![markdownd registration](https://cloud.githubusercontent.com/assets/12871120/20036611/a47fdb94-a40c-11e6-8211-2e375ded2a44.jpg)

**Comment by lauer3912** [comment]
@1iveowl 
We have sent a new registration code to you, please check your email.
I'm sorry! The registration code sent by the order system is incorrect. New registration code, please try! There should be no problem.

**Comment by 1iveowl** [comment]
Thanks. The new registration code works.
