### ISSUE TITLE
Emojis won't load

### ISSUE THREAD

**Issue by nmaxcom** [Romanysoft/MarkdownD#5]
Hi. First of all, great app. I've tried many (I think all of them), and this is the one, so thanks for developing this.

This is the issue, though:

<img width="920" alt="ff652a52499546aa83363782c574e48e" src="https://cloud.githubusercontent.com/assets/8936090/20242690/526a70fe-a938-11e6-90b1-e3bbc96417ee.png">

The other two tabs load well. I've updated to last version and reinstalled it etc but still happening.

**Comment by lauer3912** [comment]
@nmaxcom 

New version fixed it.
